export default {
  CHANGE_TAG_NAME: 'CHANGE_TAG_NAME',
  SUBMIT_TAG_NAME: 'SUBMIT_TAG_NAME',
  DISPLAY_TAG: 'DISPLAY_TAG',
  REMOVE_TAG: 'REMOVE_TAG',
  TOGGLE_DISPLAY_TAGSELECT: 'TOGGLE_DISPLAY_TAGSELECT',
  SELECT_TAG_COLOR: 'SELECT_TAG_COLOR',
  SUBMIT_TAG: 'SUBMIT_TAG',
};
