export default {
  CHANGE_TAG_NAME: 'CHANGE_TAG_NAME',
  SUBMIT_TAG_NAME: 'SUBMIT_TAG_NAME',
  DISPLAY_TAG: 'DISPLAY_TAG',
  REMOVE_TAG: 'REMOVE_TAG',
  SET_DROPDOWN_DISPLAY: 'SET_DROPDOWN_DISPLAY',
  SELECT_TAG_COLOR: 'SELECT_TAG_COLOR',
  SUBMIT_TAG: 'SUBMIT_TAG',
};
